# Generated by Django 4.0.4 on 2025-08-26 15:13

from django.db import migrations, models
import esfa_eyes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EsfaEyes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='1404', max_length=4, verbose_name='year')),
                ('financial_info', models.JSONField(default=esfa_eyes.models.default_financial_info)),
                ('international_finance_info', models.JSONField(default=esfa_eyes.models.default_international_finance_info)),
                ('international_sales_info', models.JSONField(default=esfa_eyes.models.default_international_sales_info)),
                ('products_info', models.JSONField(default=esfa_eyes.models.default_products_info)),
            ],
        ),
    ]
