# Generated by Django 4.0.4 on 2025-09-26 12:46

from django.db import migrations, models
import esfa_eyes.models


class Migration(migrations.Migration):

    dependencies = [
        ('esfa_eyes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='esfaeyes',
            name='kavosh_products_info',
            field=models.JSONField(default=esfa_eyes.models.default_kavosh_products_info),
        ),
        migrations.AddField(
            model_name='esfaeyes',
            name='kia_products_info',
            field=models.JSONField(default=esfa_eyes.models.default_kia_products_info),
        ),
    ]
