# Generated by Django 4.0.4 on 2025-10-04 08:06

from django.db import migrations
from esfa_eyes.models import EsfaEyes
from esfa_eyes.models import default_kia_products_info

def migrate_kia_products_info(apps, schema_editor):    
    for esfa_eye in EsfaEyes.objects.all():
        old_kia_info = esfa_eye.kia_products_info
        
        new_kia_info = default_kia_products_info()
        
        if old_kia_info:
            if "unproduced_kia_workshop_inventory" in old_kia_info:
                old_unproduced = old_kia_info["unproduced_kia_workshop_inventory"]
                if isinstance(old_unproduced, dict):
                    for key in ["121", "131", "Kia Meter"]:
                        if key in old_unproduced["_info"]:
                            new_kia_info["unproduced_kia_workshop_inventory"]["_info"][key] = old_unproduced["_info"][key]
            
            if "ready_kia_products" in old_kia_info:
                old_ready = old_kia_info["ready_kia_products"]
                if isinstance(old_ready, dict):
                    for key in ["121", "131", "Kia Meter"]:
                        if key in old_ready["_info"]:
                            new_kia_info["ready_kia_products"]["_info"][key] = old_ready["_info"][key]
        
        esfa_eye.kia_products_info = new_kia_info
        esfa_eye.save()

class Migration(migrations.Migration):

    dependencies = [
        ('esfa_eyes', '0002_esfaeyes_kavosh_products_info_and_more'),
    ]

    operations = [
        migrations.RunPython(
            migrate_kia_products_info,
        ),
    ]
