# Generated by Django 4.0.4 on 2025-10-04 09:36

from django.db import migrations
from esfa_eyes.models import EsfaEyes

def update_esfaeyes_product_info(apps, schema_editor):    
    for esfa_eye in EsfaEyes.objects.all():        
        
        individual_sales_fields = [
            "individual_sales",
            "individual_sales_quantities", 
            "individual_sales_total_received",
            "individual_sales_check_received",
            "individual_sales_unknown"
        ]
        for field_name in individual_sales_fields:
            if field_name in esfa_eye.financial_info:
                current_data = esfa_eye.financial_info[field_name]['_info']
                
                for key in ["Nira48-600", "Nira110-600"]:
                    if key not in current_data:
                        current_data[key] = 0

                esfa_eye.financial_info[field_name]['_info'] = current_data
        
        
        if "china_production_orders" in esfa_eye.international_finance_info:
            current_data = esfa_eye.international_finance_info["china_production_orders"]['_info']
            
            for key in ["Nira48-600", "Nira110-600"]:
                if key not in current_data:
                    current_data[key] = 0
            
            esfa_eye.international_finance_info["china_production_orders"]['_info'] = current_data

        if "turkiye_inventory" in esfa_eye.international_sales_info:
            current_data = esfa_eye.international_sales_info["turkiye_inventory"]['_info']
            
            for key in ["Nira48-600", "Nira110-600"]:
                if key not in current_data:
                    current_data[key] = 0
            
            esfa_eye.international_sales_info["turkiye_inventory"]['_info'] = current_data
            
        esfa_eye.save()

            
        

class Migration(migrations.Migration):

    dependencies = [
        ('esfa_eyes', '0003_auto_20251004_1136'),
    ]

    operations = [
        migrations.RunPython(update_esfaeyes_product_info),
    ]
