# Generated by Django 4.0.4 on 2025-10-06 10:56

from django.db import migrations


def update_all_esfa_eyes_records(apps, schema_editor):
    # Resolve the model through apps.get_model so this historical migration does not
    # query columns that later migrations add (which breaks a fresh database, test
    # runs included). update_user_access() is a live-model method that the historical
    # model does not carry, so import the real model only when there is a row to
    # update -- on a fresh/empty database this is a no-op.
    HistoricalEsfaEyes = apps.get_model("esfa_eyes", "EsfaEyes")
    if not HistoricalEsfaEyes.objects.exists():
        return

    from esfa_eyes.models import EsfaEyes

    for record in EsfaEyes.objects.all():
        record.update_user_access()
        record.save()

class Migration(migrations.Migration):

    dependencies = [
        ('esfa_eyes', '0004_auto_20251004_1306'),
    ]

    operations = [
        migrations.RunPython(
            update_all_esfa_eyes_records
        ),
    ]
