# Generated by Django 4.0.4 on 2025-10-08 05:01

from django.db import migrations
from esfa_eyes.models import EsfaEyes
from esfa_eyes.schemas.esfa_eyes_info import EsfaEyesProductInfo

users_with_kia_products_info_access = ['Kazempourian']

def add_kia_99(apps, schema_editor):    
    for record in EsfaEyes.objects.all():        
        if (hasattr(record, 'kia_products_info') and 
            record.kia_products_info and not
            'deliverd_1399' in record.kia_products_info):

            record.kia_products_info['deliverd_1399'] = EsfaEyesProductInfo({
						"121": 0,
						"131": 0,
						"Kia Meter": 0,
						"Nira48-600": 0,
						"Nira110-600": 0,
					},update_interval_days=180, who_can_see=users_with_kia_products_info_access).__dict__
            record.save()

class Migration(migrations.Migration):

    dependencies = [
        ('esfa_eyes', '0006_update_balance_dollar_fields'),
    ]

    operations = [
        migrations.RunPython(
            add_kia_99,
        ),
    ]
