# Generated by Django 4.0.4 on 2025-10-11 15:36

from django.db import migrations
from esfa_eyes.models import EsfaEyes

def update_all_esfa_eyes_records(apps, schema_editor):    
    for record in EsfaEyes.objects.all():
        record.update_user_access()
        record.save()

class Migration(migrations.Migration):

    dependencies = [
        ('esfa_eyes', '0008_update_esfa_eyes_user_access'),
    ]

    operations = [
        migrations.RunPython(
            update_all_esfa_eyes_records
        ),
    ]
