# Generated by Django 4.0.4 on 2025-10-20 11:48

from django.db import migrations
from esfa_eyes.models import EsfaEyes
from esfa_eyes.schemas.esfa_eyes_info import EsfaEyesInfo

users_with_financial_info_access = ['Amiri']

def add_total_insured_non_staffs(apps, schema_editor):    
    for record in EsfaEyes.objects.all():  
        if record.financial_info and not 'total_insured_non_staffs' in record.financial_info:
            record.financial_info['total_insured_non_staffs'] = EsfaEyesInfo(0, 31, who_can_see=users_with_financial_info_access).__dict__
            record.save()


class Migration(migrations.Migration):

    dependencies = [
        ('esfa_eyes', '0009_update_esfa_eyes_user_access'),
    ]

    operations = [
        migrations.RunPython(
            add_total_insured_non_staffs,
        ),
    ]
