# Generated by Django 4.0.4 on 2026-01-07 17:32

from django.db import migrations
from esfa_eyes.models import EsfaEyes
from esfa_eyes.models import EsfaEyes, default_products_info, default_kia_products_info, default_kavosh_products_info

def add_shortage_fields(apps, schema_editor):    
    for record in EsfaEyes.objects.all():
        if 'unproducable_shortage_product' not in record.products_info:
            record.products_info['unproducable_shortage_product'] = default_products_info()['unproducable_shortage_product']
        
        if 'unproducable_shortage_kia_product' not in record.kia_products_info:
            record.kia_products_info['unproducable_shortage_kia_product'] = default_kia_products_info()['unproducable_shortage_kia_product']
        
        if 'unproducable_shortage_kavosh_product' not in record.kavosh_products_info:
            record.kavosh_products_info['unproducable_shortage_kavosh_product'] = default_kavosh_products_info()['unproducable_shortage_kavosh_product']
        
        record.save()

class Migration(migrations.Migration):

    dependencies = [
        ('esfa_eyes', '0010_add_total_insured_non_staffs'),
    ]

    operations = [
        migrations.RunPython(
            add_shortage_fields,
        ),
    ]
