# Generated by Django 4.0.4 on 2026-04-11 14:11

from django.db import migrations, models
import esfa_eyes.models


class Migration(migrations.Migration):

    dependencies = [
        ('esfa_eyes', '0011_add_shortage_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='esfaeyes',
            name='Captan_series_sales_info',
            field=models.JSONField(default=esfa_eyes.models.default_Captan_series_sales_info),
        ),
        migrations.AddField(
            model_name='esfaeyes',
            name='MCM_series_sales_info',
            field=models.JSONField(default=esfa_eyes.models.default_MCM_series_sales_info),
        ),
        migrations.AddField(
            model_name='esfaeyes',
            name='kavosh_series_sales_info',
            field=models.JSONField(default=esfa_eyes.models.default_kavosh_series_sales_info),
        ),
    ]
