# Generated by Django 4.0.4 on 2026-04-11 17:19

from django.db import migrations

def add_is_editable_to_json_fields(apps, schema_editor):
    EsfaEyes = apps.get_model('esfa_eyes', 'EsfaEyes')

    # The JSON fields we need to process
    json_fields = [
        'financial_info',
        'international_finance_info',
        'international_sales_info',
        'products_info',
        'kavosh_products_info',
        'kia_products_info',
        'Captan_series_sales_info',
        'kavosh_series_sales_info',
        'MCM_series_sales_info',
    ]

    def recursive_add_is_editable(data):
        """Recursively add 'is_editable': True to any dict that appears to be an EsfaEyesInfo-like object."""
        if isinstance(data, dict):
            # Heuristic: an EsfaEyesInfo dict contains '_info' and 'UPDATE_INTERVAL_DAYS'
            if '_info' in data and 'UPDATE_INTERVAL_DAYS' in data:
                if 'is_editable' not in data:
                    data['is_editable'] = True
            # Recurse into nested dictionaries
            for key, value in data.items():
                recursive_add_is_editable(value)
        elif isinstance(data, list):
            for item in data:
                recursive_add_is_editable(item)

    for obj in EsfaEyes.objects.all():
        changed = False
        for field in json_fields:
            field_data = getattr(obj, field)
            if field_data is not None:
                # Make a deep copy to avoid accidental mutation issues
                import copy
                original = copy.deepcopy(field_data)
                recursive_add_is_editable(field_data)
                if original != field_data:
                    setattr(obj, field, field_data)
                    changed = True
        if changed:
            obj.save(update_fields=json_fields)

def noop(apps, schema_editor):
    # Reverse migration does nothing (or you can remove the field if desired)
    pass

class Migration(migrations.Migration):
    dependencies = [
        ('esfa_eyes', '0012_esfaeyes_captan_series_sales_info_and_more'),  # Replace with actual previous migration name
    ]

    operations = [
        migrations.RunPython(add_is_editable_to_json_fields, noop),
    ]