# Generated by Django 4.0.4 on 2025-08-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0030_user_first_name_p_user_last_name_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_FinancialManager',
            field=models.BooleanField(default=False, verbose_name='is_FinancialManager'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_ProjectReportManager',
            field=models.BooleanField(default=False, verbose_name='is_ProjectReportManager'),
        ),
    ]
