# Generated by Django 4.0.4 on 2025-08-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0031_user_is_financialmanager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_InternationalFinanceManager',
            field=models.BooleanField(default=False, verbose_name='is_InternationalFinanceManager'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_InternationalSalesManager',
            field=models.BooleanField(default=False, verbose_name='is_InternationalSalesManager'),
        ),
    ]
