# Generated by Django 4.0.4 on 2025-08-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0032_user_is_internationalfinancemanager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ProductionManager',
            field=models.BooleanField(default=False, verbose_name='is_ProductionManager'),
        ),
    ]
