# Generated by Django 4.0.4 on 2025-09-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0033_user_is_productionmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_PaymentManager',
            field=models.BooleanField(default=False, verbose_name='is_FinancialManager'),
        ),
    ]
