# Generated by Django 4.0.4 on 2025-09-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0034_user_is_paymentmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_PaymentManager',
            field=models.BooleanField(default=False, verbose_name='is_PaymentManager'),
        ),
    ]
