# Generated by Django 4.0.4 on 2025-09-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0035_alter_user_is_paymentmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ProductionManagerR131',
            field=models.BooleanField(default=False, verbose_name='is_ProductionManager'),
        ),
    ]
