# Generated by Django 4.0.4 on 2025-09-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0036_user_is_productionmanagerr131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_ProductionManagerR131',
        ),
        migrations.AddField(
            model_name='user',
            name='is_KavoshProductionManager',
            field=models.BooleanField(default=False, verbose_name='is_KavoshProductionManager'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_KiaProductionManager',
            field=models.BooleanField(default=False, verbose_name='is_KiaProductionManager'),
        ),
    ]
