# Generated by Django 4.0.4 on 2025-09-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0036_user_is_productionmanagerr131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_ProductionManagerR131',
            new_name='is_ProductionManagerReadonly',
        ),
        migrations.AddField(
            model_name='user',
            name='is_R131ProductionManager',
            field=models.BooleanField(default=False, verbose_name='is_ProductionManager'),
        ),
    ]
