# Generated by Django 4.0.4 on 2025-09-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0037_rename_is_productionmanagerr131_user_is_productionmanagerreadonly_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_ProductionManagerReadonly',
            field=models.BooleanField(default=False, verbose_name='is_ProductionManagerReadonly'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_R131ProductionManager',
            field=models.BooleanField(default=False, verbose_name='is_R131ProductionManager'),
        ),
    ]
