# Generated by Django 4.0.4 on 2025-10-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0037_remove_user_is_productionmanagerr131_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_FinancialManager_readonly',
            field=models.BooleanField(default=False, verbose_name='is_FinancialManager_readonly'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_InternationalFinanceManager_readonly',
            field=models.BooleanField(default=False, verbose_name='is_InternationalFinanceManager_readonly'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_InternationalSalesManager_readonly',
            field=models.BooleanField(default=False, verbose_name='is_InternationalSalesManager_readonly'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_KavoshProductionManager_readonly',
            field=models.BooleanField(default=False, verbose_name='is_KavoshProductionManager_readonly'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_KiaProductionManager_readonly',
            field=models.BooleanField(default=False, verbose_name='is_KiaProductionManager_readonly'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_ProductionManager_readonly',
            field=models.BooleanField(default=False, verbose_name='is_ProductionManager_readonly'),
        ),
    ]
