# Generated by Django 4.0.4 on 2025-10-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0038_user_is_financialmanager_readonly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_global_sales_editor',
            field=models.BooleanField(default=False, verbose_name='is_global_sales_editor'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_global_sales_viewer',
            field=models.BooleanField(default=False, verbose_name='is_global_sales_viewer'),
        ),
    ]
