# Generated by Django 4.0.4 on 2026-01-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0039_user_is_global_sales_editor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_detailed_sales_editor',
            field=models.BooleanField(default=False, verbose_name='is_detailed_sales_editor'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_detailed_sales_viewer',
            field=models.BooleanField(default=False, verbose_name='is_detailed_sales_viewer'),
        ),
    ]
