# Generated by Django 4.0.4 on 2026-01-28 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0040_user_is_detailed_sales_editor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_detailed_sales_editor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_global_sales_editor',
        ),
    ]
