# Generated by Django 4.0.4 on 2026-01-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0041_remove_user_is_detailed_sales_editor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff_info_viewer',
            field=models.BooleanField(default=False, verbose_name='is_staff_info_viewer'),
        ),
    ]
