# Generated by Django 4.0.4 on 2026-02-21 09:58

from django.db import migrations
from sheets.models import Sheet

def update_sheet_user_names(apps, schema_editor):
    sheets_to_update = []

    for sheet in Sheet.objects.all():
        if sheet.user:
            full_name = sheet.user.get_full_name()
            if sheet.user_name != full_name:  # Only update if changed
                sheet.user_name = full_name
                sheets_to_update.append(sheet)
    
    if sheets_to_update:
        Sheet.objects.bulk_update(sheets_to_update, ['user_name'])

class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0042_user_is_staff_info_viewer'),
    ]

    operations = [
        migrations.RunPython(update_sheet_user_names),
    ]