# Generated by Django 4.0.4 on 2026-02-21 09:58

from django.db import migrations

def update_sheet_user_names(apps, schema_editor):
    Sheet = apps.get_model('sheets', 'Sheet')
    sheets_to_update = []

    for sheet in Sheet.objects.all():
        if sheet.user:
            # Replicate get_full_name() using first_name and last_name fields
            full_name = f"{sheet.user.first_name or ''} {sheet.user.last_name or ''}".strip()
            
            if sheet.user_name != full_name:
                sheet.user_name = full_name
                sheets_to_update.append(sheet)
    
    if sheets_to_update:
        Sheet.objects.bulk_update(sheets_to_update, ['user_name'])

class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0042_user_is_staff_info_viewer'),
    ]

    operations = [
        migrations.RunPython(update_sheet_user_names),
    ]