# Generated by Django 4.0.4 on 2026-02-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0044_add_description_to_sheet_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auto_hour_ID',
            field=models.IntegerField(blank=True, null=True, verbose_name='auto_hour_ID'),
        ),
    ]
