# Generated by Django 4.0.4 on 2026-02-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0047_populate_auto_hour_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_HourVerifier',
            field=models.BooleanField(default=False, verbose_name='is_HourVerifier'),
        ),
    ]
