# Generated by Django 4.0.4 on 2026-02-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0048_user_is_hourverifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='is_verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='staff_group_tag',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='staff_group_tag'),
        ),
        migrations.AddField(
            model_name='user',
            name='verifier_group_tags',
            field=models.CharField(blank=True, default='', help_text='Comma-separated tags this verifier can see', max_length=255, verbose_name='verifier_group_tags'),
        ),
    ]
