# Generated by Django 4.0.4 on 2026-02-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0049_sheet_is_verified_user_staff_group_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='is_supreme_verified',
            field=models.BooleanField(default=False, verbose_name='is_supreme_verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_SupremeHourVerifier',
            field=models.BooleanField(default=False, verbose_name='is_SupremeHourVerifier'),
        ),
    ]
