# Generated by Django 5.2.14 on 2026-05-10 17:19

from django.db import migrations

def add_attendance_field(apps, schema_editor):
    Sheet = apps.get_model('sheets', 'Sheet')
    for sheet in Sheet.objects.all():
        data = sheet.data
        updated = False
        for data_item in data:
            if 'Attendance' not in data_item:
                data_item['Attendance'] = ""
                updated = True
        if updated:
            sheet.save(update_fields=['data'])

class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0050_sheet_is_supreme_verified_and_more'),
    ]

    operations = [
        migrations.RunPython(add_attendance_field),
    ]
