# Generated by Django 5.2.14 on 2026-07-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0052_hour_approval_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='remote_percentage',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='remote_percentage'),
        ),
    ]
